version: '3.1'
services:
  wordpress:
    image: wordpress:${WORDPRESS_VERSION}-php${PHP_VERSION}
    restart: always
    ports:
      - "${WP_HTTP_PORT}:80"
    environment:
      - WORDPRESS_DB_NAME=${DB_NAME}
      - WORDPRESS_DB_USER=${DB_USER}
      - WORDPRESS_DB_PASSWORD=${DB_PASSWORD}
      - WORDPRESS_DB_HOST=mysql
      - WORDPRESS_DEBUG=${WORDPRESS_DEBUG}
      - WORDPRESS_CONFIG_EXTRA=${WORDPRESS_CONFIG_EXTRA}
    volumes:
      - '${APP_CODE_PATH_HOST}:/var/www/html'
  mysql:
    image: mariadb:10.5
    environment:
      - 'MARIADB_DATABASE=${DB_NAME}'
      - 'MARIADB_USER=${DB_USER}'
      - 'MARIADB_PASSWORD=${DB_PASSWORD}'
      - 'MARIADB_ROOT_PASSWORD=${DB_PASSWORD}'
    volumes:
      - '${DATA_PATH_HOST}:/var/lib/mysql'
    ports:
      - '${MYSQL_PORT}:3306'
volumes:
  db:
