#User defined
user:
  wordpress:
    label:
      Wordpress version
    hint:
      Select a Wordpress version from the list above.
      Wordpress & PHP compatibility; https://make.wordpress.org/core/handbook/references/php-compatibility-and-wordpress-versions/
    type:
      select
    values:
      - "6.0"
      - "5.9"
      - "5.8"
      - "5.7"
      - "5.6"
    target:
      WORDPRESS_VERSION

  fake_name:
    label:
      PHP version
    hint:
      Select a PHP version from the list above.
      Wordpress & PHP compatibility; https://make.wordpress.org/core/handbook/references/php-compatibility-and-wordpress-versions/
    type:
      select
    values:
      - "8.1"
      - "8.0"
      - "7.4"
    target:
      PHP_VERSION

  MariaDB_version:
    label:
      MariaDB version
    hint:
      Select a MariaDB version from the list above
    type:
      select
    values:
      - latest
      - 10.7
      - 10.6
      - 10.5
    target:
      MARIADB_VERSION

  wp_debug:
    label:
      Enable WordPress debug and log mode?
    type:
      checkbox
    hint:
      Check to enable WordPress debug mode
    target:
      WORDPRESS_DEBUG_LOG

  xdebug:
    label:
      Enable XDebug 3 mode?
    type:
      checkbox
    hint:
      Check to enable XDebug 3 mode
    target:
      XDEBUG

#  wp_config_extra:
#    label:
#      Add extra define to 'wp-config.php'?
#    hint:
#      An example - define('WP_DEBUG_DISPLAY', false);
#    type:
#      input
#    target:
#      WORDPRESS_CONFIG_EXTRA

#System defaults
system:
  show_localpath_selector:
    true
  db_credentials:
    true
  ports:
    http:
      WP_HTTP_PORT
    others:
      - MYSQL_PORT
      - PMA_PORT