#User defined
user:
  wordpress_version:
    label:
      Wordpress/PHP version
    hint:
      Select a combination of Wordpress and PHP from the list above.
    type:
      select
    values:
      - "6.0-php8.1" # WP: 6.0, PHP: 8.1
      - "6.0-php8.0" # WP: 6.0, PHP: 8.0
      - "6.0-php7.4" # WP: 6.0, PHP: 7.4
      - "5.9-php8.1" # WP: 5.9, PHP: 8.1
      - "5.9-php8.0" # WP: 5.9, PHP: 8.0
      - "5.9-php7.4" # WP: 5.9, PHP: 7.4
      - "5.8-php8.0" # WP: 5.8, PHP: 8.0
      - "5.8-php7.4" # WP: 5.8, PHP: 7.4
      - "5.7-php8.0" # WP: 5.7, PHP: 8.0
      - "5.7-php7.4" # WP: 5.7, PHP: 7.4
      - "5.6-php8.0" # WP: 5.6, PHP: 8.0
      - "5.6-php7.4" # WP: 5.6, PHP: 7.4
    target:
      WORDPRESS_IMAGE

#  wordpress_version:
#    label:
#      Wordpress version
#    hint:
#      Select a Wordpress version from the list above.
#      Check for PHP & Wordpress compatibility here; https://make.wordpress.org/core/handbook/references/php-compatibility-and-wordpress-versions/
#    type:
#      select
#    values:
#      - "6.0" # PHP >= 8.1
#      - "5.9" # PHP >= 8.1
#      - "5.8" # PHP >= 8.0
#      - "5.7" # PHP >= 8.0
#      - "5.6" # PHP >= 8.0
##      - "5.5" # PHP >= 7.4
##      - "5.4" # PHP >= 7.4
##      - "5.3" # PHP >= 7.4
#    target:
#      WORDPRESS_VERSION
#
#  php_version:
#    label:
#      PHP version
#    hint:
#      Select a PHP version from the list above.
#      Check for PHP & Wordpress compatibility here; https://make.wordpress.org/core/handbook/references/php-compatibility-and-wordpress-versions/
#    type:
#      select
#    values:
#      - "8.1"
#      - "8.0"
##      - "7.4"
#    target:
#      PHP_VERSION
      
  MariaDB_version:
    label:
      MariaDB version
    hint:
      Select a MariaDB version from the list above
    type:
      select
    values:
      - latest
      - 10.7
      - 10.6
      - 10.5
    target:
      MARIADB_VERSION
      
  wp_debug:
    label:
      Enable WordPress debug mode?
    type:
      checkbox
    hint:
      Check to enable WordPress debug mode
    target:
      WORDPRESS_DEBUG

  wp_debug_log:
    label:
      Enable WordPress debug log?
    type:
      checkbox
    hint:
      Check to enable WordPress debug log
    target:
      WORDPRESS_DEBUG_LOG

  wp_debug_display:
    label:
      Enable WordPress debug display?
    type:
      checkbox
    hint:
      Check to enable WordPress debug display
    target:
      WORDPRESS_DEBUG_DISPLAY


#System defaults
system:
  show_localpath_selector:
    true
  #For collecting and storing DB in .env
  #db/user/password
  db_credentials:
    true
  #Generate public ports for the docker image
  ports:
    http:
      WP_HTTP_PORT
    others:
      - MYSQL_PORT
      - PMA_PORT