#User defined
user:
  wordpress_version:
    label:
      Wordpress version
    hint:
      Select a Wordpress version from the list above.
      Wordpress & PHP compatibility; https://make.wordpress.org/core/handbook/references/php-compatibility-and-wordpress-versions/
    type:
      select
    values:
      - "6.0" # PHP >= 8.1
      - "5.9" # PHP >= 8.1
      - "5.8" # PHP >= 8.0
      - "5.7" # PHP >= 8.0
      - "5.6" # PHP >= 8.0
      - "5.5" # PHP >= 7.4
      - "5.4" # PHP >= 7.4
      - "5.3" # PHP >= 7.4
    target:
      WORDPRESS_VERSION

  php_version:
    label:
      PHP version
    hint:
      Select a PHP version from the list above.
      Wordpress & PHP compatibility; https://make.wordpress.org/core/handbook/references/php-compatibility-and-wordpress-versions/
    type:
      select
    values:
      - "8.1"
      - "8.0"
      - "7.4"
    target:
      PHP_VERSION
      
  wp_debug:
    label:
      Enable WordPress debug mode?
    type:
      checkbox
    hint:
      Check to enable WordPress debug mode
    target:
      WORDPRESS_DEBUG

  wp_config_extra:
    label:
      Add extra define to 'wp-config.php'?
    type:
      input
    hint:
      An example: define('WP_DEBUG_LOG', true);
    target:
      WORDPRESS_CONFIG_EXTRA


#System defaults
system:
  show_localpath_selector:
    true
  #For collecting and storing DB in .env
  #db/user/password
  db_credentials:
    true
  #Generate public ports for the docker image
  ports:
    http:
      WP_HTTP_PORT
    others:
      - MYSQL_PORT
      - PMA_PORT