FROM wordpress:5.9-php8.1
ARG XDEBUG

RUN apt-get update && \
    apt-get -y install git

RUN if [ "$XDEBUG" = true ] ; then \
    cd /tmp && \
    git clone https://github.com/xdebug/xdebug.git && \
    cd xdebug && \
    git checkout xdebug_3_1 && \
    phpize && \
    ./configure --enable-xdebug && \
    make && \
    make install && \
    rm -rf /tmp/xdebug \
;fi

RUN if [ "$XDEBUG" = true ] ; then \
    COPY files-to-copy/ / \
;fi

RUN if [ "$XDEBUG" = true ] ; then \
    docker-php-ext-enable xdebug \
;fi
